//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTypeImport
    {
        public int Id { get; set; }
        public int IdProductType { get; set; }
        public double CoefOfType { get; set; }
    
        public virtual TypeOfProduction TypeOfProduction { get; set; }
    }
}
